[tool.poetry]
name = "supermarket-price-tracker"
version = "0.1.0"
description = ""
authors = ["roedebaron <45661813+roedebaron@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.28.2"
python-dateutil = "^2.8.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
