version: "3.8"

name: supermarket-price-tracker

services:
    app:
        build:
            context: ..
            dockerfile: docker/Dockerfile
        volumes:
            - ../data:/app/data
        environment:
            - PYTHONUNBUFFERED=1 # Prevents Python from buffering stdout and stderr
